create table vartotojas (id integer generated by default as identity, tel_nr varchar(255), vardas varchar(255), primary key (id));
create table veiksmai (id integer generated by default as identity, data varchar(255), vartotojo_id integer, veiksmas varchar(255), primary key (id));

INSERT INTO Vartotojas VALUES(1, '37054', 'Tomas');
INSERT INTO Vartotojas VALUES(2, '38045', 'Jonas');
INSERT INTO Vartotojas VALUES(3, '39074', 'Petras');


INSERT INTO Veiksmai VALUES(1, '2021-10-01', 1,'insert');
INSERT INTO Veiksmai VALUES(2, '2021-10-01', 2,'update');
INSERT INTO Veiksmai VALUES(3, '2021-10-01', 3,'delete');
INSERT INTO Veiksmai VALUES(4, '2021-11-01', 1,'insert');
INSERT INTO Veiksmai VALUES(5, '2021-11-01', 2,'delete');
INSERT INTO Veiksmai VALUES(6, '2021-12-01', 3,'update');


